import React, {useEffect,useMemo,useState} from 'react';
import ReactDOM from 'react-dom/client';
import {ArrowRight,CheckCircle2,Eye,Gauge,Heart,Info,Pause,Play,RefreshCw,RotateCcw,Search,Share2,Shield,ShieldCheck,Sparkles,Users,Zap} from 'lucide-react';
import './styles.css';

type Metrics={reach:number;hostility:number;safety:number;trust:number};
type Choice={id:string;label:string;helper:string;kind:'risk'|'safe'|'neutral'|'support';delta:Partial<Metrics>;score:number;title:string;body:string};
type Scenario={id:string;title:string;tag:string;intro:string;post:string;prompt:string;choices:Choice[];peace:Choice[];xray:{t:string;s:string;b:string}[];shield?:string[]};

const base:Metrics={reach:48,hostility:34,safety:70,trust:66};
const scenarios:Scenario[]=[
{id:'clip',title:'The Cropped Clip',tag:'Misinformation · Interfaith tension',intro:'A dramatic clip is moving fast through Nodi. The caption is certain. The source is not.',post:'“Everyone needs to see this NOW.” A 9-second cropped clip claims a local religious group attacked a community event. No original upload or location is shown.',prompt:'Your friend sends this to a group chat. What do you do first?',choices:[
{id:'share',label:'Share now',helper:'Pass it on before it disappears',kind:'risk',delta:{reach:28,hostility:24,safety:-17,trust:-20},score:8,title:'Speed beats context',body:'The clip reaches more feeds and comments shift from the event to broad claims about an entire community.'},
{id:'comment',label:'Post an angry comment',helper:'Call the group out publicly',kind:'risk',delta:{reach:14,hostility:30,safety:-19,trust:-23},score:12,title:'The frame hardens',body:'Your comment becomes social proof and replies repeat the same identity framing without checking the clip.'},
{id:'verify',label:'Verify the source',helper:'Pause and look for original context',kind:'safe',delta:{reach:-6,hostility:-8,safety:8,trust:12},score:82,title:'The spread slows',body:'You notice the clip begins mid-scene and the source remains unclear, so you do not amplify it.'},
{id:'ignore',label:'Ignore it',helper:'Do not interact',kind:'neutral',delta:{reach:2,hostility:5,safety:-2,trust:-3},score:38,title:'You do not add fuel',body:'You avoid amplifying the post, but the misleading framing continues unchecked in your group.'}],
peace:[
{id:'trace',label:'Trace the original source',helper:'Check full clip, date and uploader',kind:'safe',delta:{reach:-14,hostility:-13,safety:14,trust:20},score:96,title:'Context becomes visible',body:'You cannot verify the original claim. You stop the chain and keep the uncertainty explicit.'},
{id:'context',label:'Add calm context',helper:'Flag uncertainty without repeating the accusation',kind:'support',delta:{reach:-8,hostility:-18,safety:12,trust:18},score:90,title:'The temperature drops',body:'People see a clear reminder that the source is unverified and group-wide conclusions are unsafe.'},
{id:'pause',label:'Pause and do not amplify',helper:'Wait for reliable context',kind:'safe',delta:{reach:-10,hostility:-8,safety:9,trust:12},score:78,title:'One less acceleration point',body:'The clip does not gain another share through you.'}],
xray:[
{t:'Emotional urgency',s:'“NOW”',b:'Urgency can push people to act before they verify.'},
{t:'Missing source',s:'No original upload',b:'A repost is not a source. Look for the earliest verifiable version.'},
{t:'Cropped context',s:'9 seconds only',b:'Short clips can hide what happened immediately before or after.'},
{t:'Social proof',s:'713 shares',b:'Popularity can feel like evidence, but engagement does not verify a claim.'},
{t:'Identity framing',s:'Whole-group blame',b:'A claim about an event can become a claim about an entire community.'}]},
{id:'meme',title:'The Viral Meme',tag:'Cyberbullying · Gendered harassment',intro:'A “joke” about a fictional student is becoming a pile-on. The crowd keeps making it harsher.',post:'A meme mocks fictional student Rima after a class presentation. Replies turn sexualized and a screenshot hints that hostile DMs have started.',prompt:'You know Rima casually. What is your first move?',choices:[
{id:'laugh',label:'React with a laugh',helper:'It is “just a meme”',kind:'risk',delta:{reach:15,hostility:21,safety:-18,trust:-12},score:10,title:'The crowd reads approval',body:'Another reaction adds social proof and lowers the social cost for others to join.'},
{id:'reshare',label:'Re-share it',helper:'Send it to another chat',kind:'risk',delta:{reach:26,hostility:24,safety:-23,trust:-17},score:4,title:'The target loses control of reach',body:'The meme escapes its original context and more strangers join in.'},
{id:'ignore',label:'Keep scrolling',helper:'Stay out of it',kind:'neutral',delta:{reach:4,hostility:8,safety:-5,trust:-4},score:42,title:'You avoid adding harm',body:'The pile-on continues, but you do not make it worse.'},
{id:'check',label:'Check on Rima privately',helper:'Ask what support she wants',kind:'support',delta:{reach:-2,hostility:-5,safety:14,trust:12},score:88,title:'Support becomes target-led',body:'You ask what she wants and avoid recirculating the meme.'}],
peace:[
{id:'support',label:'Support + report',helper:'Check in, preserve only needed evidence, report',kind:'support',delta:{reach:-8,hostility:-14,safety:20,trust:17},score:98,title:'The response follows the target',body:'You support without turning the abuse into more content.'},
{id:'interrupt',label:'Interrupt the pile-on calmly',helper:'Set a boundary without attacking back',kind:'safe',delta:{reach:-5,hostility:-19,safety:14,trust:18},score:92,title:'A social norm becomes visible',body:'A calm response refuses the joke frame and lowers the temperature.'},
{id:'private',label:'Offer private support first',helper:'Ask what she wants before public action',kind:'support',delta:{reach:-2,hostility:-7,safety:18,trust:14},score:91,title:'Agency stays with the target',body:'Rima can decide what kind of support she wants.'}],
xray:[
{t:'“Just joking” shield',s:'Humor frame',b:'Humor can disguise social punishment.'},
{t:'Pile-on effect',s:'Crowd repetition',b:'Each small reaction lowers the cost for the next person to join.'},
{t:'Target displacement',s:'Talk about, not with',b:'Safe support restores agency to the person targeted.'},
{t:'Evidence vs recirculation',s:'Screenshot risk',b:'Preserve only what is needed. Do not spread harmful material as “evidence.”'},
{t:'Escalation cue',s:'Hostile DMs',b:'Credible threats may require trusted or official support.'}],
shield:['Recognize — name the behavior without blaming the target.','Support — check in privately and ask what the person wants.','Preserve — save only necessary evidence without recirculation.','Report — use the relevant platform or community pathway.','Escalate — credible threats may require trusted or official support.']},
{id:'voice',title:'The Missing Voice',tag:'Source diversity · Inclusion',intro:'A sweeping claim about a fictional minority community is everywhere. Everyone is speaking about them. Nobody from the community is quoted.',post:'“They do not want to integrate with the rest of us.” The post cites “people nearby” but gives no direct source, document or first-person voice.',prompt:'You are about to join the conversation. What do you do?',choices:[
{id:'share',label:'Share the outsider take',helper:'It sounds plausible',kind:'risk',delta:{reach:18,hostility:15,safety:-11,trust:-18},score:18,title:'The claim becomes the default story',body:'Repetition makes an unsupported interpretation feel settled.'},
{id:'stereo',label:'Add a stereotype',helper:'Generalize from what you heard',kind:'risk',delta:{reach:12,hostility:26,safety:-18,trust:-25},score:4,title:'A broad label replaces people',body:'The thread shifts from one claim to a fixed identity judgment.'},
{id:'source',label:'Seek a primary source',helper:'Look for direct, relevant context',kind:'safe',delta:{reach:-4,hostility:-10,safety:10,trust:17},score:86,title:'The information gap becomes visible',body:'You notice the post has no direct evidence and no first-person source.'},
{id:'pause',label:'Pause before commenting',helper:'Do not speak beyond the evidence',kind:'neutral',delta:{reach:-3,hostility:-4,safety:5,trust:7},score:60,title:'You leave room for uncertainty',body:'You avoid adding another unsupported claim while looking for better context.'}],
peace:[
{id:'first',label:'Find relevant first-person context',helper:'Use a direct source without tokenizing',kind:'support',delta:{reach:-7,hostility:-12,safety:13,trust:22},score:97,title:'The frame widens',body:'Direct context enters without making one person represent an entire community.'},
{id:'label',label:'Separate claim from evidence',helper:'State what is known, unknown and missing',kind:'safe',delta:{reach:-5,hostility:-14,safety:11,trust:20},score:95,title:'Certainty becomes accountable',body:'The thread can now distinguish interpretation from evidence.'},
{id:'amplify',label:'Amplify a credible primary source',helper:'Add context without rewriting it',kind:'support',delta:{reach:-2,hostility:-10,safety:12,trust:21},score:93,title:'The missing voice enters directly',body:'The conversation now includes direct context rather than only outsider interpretation.'}],
xray:[
{t:'Voice absence',s:'No first-person source',b:'A conversation can look diverse while excluding the people most affected.'},
{t:'Vague authority',s:'“People nearby say…”',b:'Vague attribution creates confidence without accountability.'},
{t:'Stereotype shortcut',s:'“They are…”',b:'Whole-group language turns a claim into identity judgment.'},
{t:'Tokenization risk',s:'One voice ≠ everyone',b:'One source should not become a spokesperson for a whole community.'},
{t:'Evidence boundary',s:'Known / unknown',b:'Keep the border between evidence, interpretation and uncertainty visible.'}]}
];

const clamp=(n:number)=>Math.max(0,Math.min(100,n));
const metrics=(c:Choice):Metrics=>({reach:clamp(base.reach+(c.delta.reach||0)),hostility:clamp(base.hostility+(c.delta.hostility||0)),safety:clamp(base.safety+(c.delta.safety||0)),trust:clamp(base.trust+(c.delta.trust||0))});

function App(){
 const [screen,setScreen]=useState('landing');
 const [i,setI]=useState(0); const [b,setB]=useState<Choice|null>(null); const [p,setP]=useState<Choice|null>(null);
 const [results,setResults]=useState<number[]>(()=>JSON.parse(localStorage.getItem('ripple-results')||'[]'));
 const [seen,setSeen]=useState<number[]>([]); const [shield,setShield]=useState(0);
 const s=scenarios[i]!;
 useEffect(()=>{localStorage.setItem('ripple-results',JSON.stringify(results));window.scrollTo(0,0)},[results,screen,i]);
 const next=()=>{ if(i===2){setScreen('results')} else {setI(i+1);setB(null);setP(null);setSeen([]);setShield(0);setScreen('intro')}};
 const save=()=>{if(!b||!p)return; const r=[...results];r[i]=Math.round((b.score+p.score)/2);setResults(r);setScreen('complete')};
 const mm=(c:Choice)=>metrics(c);
 const reset=()=>{localStorage.removeItem('ripple-results');setResults([]);setI(0);setB(null);setP(null);setScreen('notice')};
 const score=Math.round((results.reduce((a,n)=>a+(n||0),0)/Math.max(1,results.length)));
 return <div className="app">
 {screen!=='landing'&&screen!=='notice'&&<header><div className="brand"><span className="logo">◎</span><b>RIPPLE BD</b></div><div className="dots">{scenarios.map((x,n)=><span key={x.id} className={n<i?'done':n===i?'active':''}>{n<i?'✓':n+1}</span>)}</div><button className="icon" onClick={()=>setScreen('landing')}>×</button></header>}
 {screen==='landing'&&<main className="landing"><nav><div className="brand"><span className="logo">◎</span><div><b>RIPPLE BD</b><small>CHAOS → PEACE</small></div></div><span className="pill">৳0 software cost</span></nav><section className="hero"><div className="copy"><span className="pill">Fictional digital community · Bangladesh</span><h1>Every click has a <em>consequence.</em></h1><p>Experience how online harm spreads. Rewind the moment. Practise a safer response. See what changed.</p><div className="actions"><button className="primary" onClick={reset}>Enter Nodi <ArrowRight/></button>{results.length>0&&<button onClick={()=>setScreen(results.length===3?'results':'intro')}>Continue</button>}</div><div className="trust"><span><Gauge/> 6–8 minutes</span><span><ShieldCheck/> No login</span><span><Pause/> No sensitive story submission</span></div></div><div className="rings"><i/><i/><i/><strong><Sparkles/></strong></div></section><div className="loop">{['MIRROR','RIPPLE','REWIND','PEACE','REFLECT'].map((x,n)=><span key={x}><small>0{n+1}</small>{x}</span>)}</div></main>}
 {screen==='notice'&&<main className="center"><div className="panel notice"><ShieldCheck className="big"/><span className="eyebrow">Before you enter Nodi</span><h2>A safe simulation, not a real incident</h2><p>All scenarios are fictional composites. No real person, community or political actor is accused. You can exit any time, and no sensitive disclosure is required.</p><div className="noticegrid"><span>✓ No login or personal data</span><span>✓ Scores describe in-app choices only</span><span>✓ Simulation indicators are not real-world causal estimates</span></div><button className="primary" onClick={()=>setScreen('intro')}>I understand — enter Nodi <ArrowRight/></button></div></main>}
 {screen==='intro'&&<main className="center"><span className="eyebrow">Scenario 0{i+1} · {s.tag}</span><h2>{s.title}</h2><p className="lead">{s.intro}</p>{i===0&&<div className="nodi"><span className="logo">◎</span><div><b>Welcome to Nodi</b><small>A fictional digital community of 10,000 people. Your choices change what happens next.</small></div></div>}<button className="primary" onClick={()=>setScreen('mirror')}>See the post <ArrowRight/></button></main>}
 {screen==='mirror'&&<main className="wide grid"><section><span className="eyebrow">MIRROR · first instinct</span><h2>{s.prompt}</h2><p className="lead">No score is shown yet. Choose what you would most naturally do.</p><div className="choices">{s.choices.map(c=><button key={c.id} className={'choice '+c.kind} onClick={()=>{setB(c);setScreen('ripple')}}><span>{c.kind==='risk'?<Zap/>:c.kind==='neutral'?<Pause/>:<ShieldCheck/>}</span><div><b>{c.label}</b><small>{c.helper}</small></div><ArrowRight/></button>)}</div></section><article className="feed"><div className="feedtop"><span className="avatar">N</span><div><b>Nodi Feed</b><small>@nodi_live · now</small></div><label>SIMULATION</label></div><p>{s.post}</p><div className="visual"><Play/></div><div className="stats"><span><Heart/> 1.8k</span><span><Users/> 426</span><span><Share2/> 713</span></div></article></main>}
 {screen==='ripple'&&b&&<main className="wide"><span className="eyebrow">RIPPLE ENGINE</span><h2>One action. Multiple consequences.</h2><p className="lead">Watch how this simulation responds to your first decision.</p><div className="outcome"><div className="timeline"><span>1</span><div><small>Your click</small><b>{b.label}</b></div><span>2</span><div><small>Network effect</small><b>{b.title}</b></div><span className="human"><Heart/></span><div><small>Human consequence</small><b>{b.body}</b></div></div><div className="metrics"><small><Info/> Simulation indicators · not effect sizes</small>{(['reach','hostility','safety','trust'] as const).map(k=>{const v=mm(b)[k],d=v-base[k],good=(k==='safety'||k==='trust')?d>=0:d<=0;return <div className="metric" key={k}><div><span>{k}</span><b className={good?'good':'bad'}>{d>=0?'+':''}{d}</b></div><i><em style={{width:v+'%'}} className={good?'goodbg':'badbg'}/></i><small>{base[k]} → {v}</small></div>})}</div></div><button className="primary" onClick={()=>setScreen('reflect')}>Reflect on what changed <ArrowRight/></button></main>}
 {screen==='reflect'&&b&&<main className="center"><div className="panel"><span className="eyebrow">REFLECT</span><h2>What changed because of your action?</h2><blockquote>{b.body}</blockquote><p className="callout">The point is not to label a person “good” or “bad.” It is to make consequences visible enough to practise a different decision.</p><button className="primary" onClick={()=>setScreen('rewind')}>Rewind the moment <RotateCcw/></button></div></main>}
 {screen==='rewind'&&<main className="center"><div className="panel rewind"><div className="miniRings"><i/><i/><i/><RotateCcw/></div><span className="eyebrow">REWIND</span><h2>You saw the ripple. Now change the first click.</h2><p className="lead">The timeline is yours again. Practise a response that protects context, people and trust.</p><button className="primary" onClick={()=>setScreen('peace')}>Try the PEACE path <ArrowRight/></button></div></main>}
 {screen==='peace'&&<main className="center"><span className="eyebrow">PEACE · practise again</span><h2>Choose a safer path.</h2><p className="lead">Safer responses can have trade-offs. The goal is evidence-informed practice.</p><div className="choices">{s.peace.map(c=><button key={c.id} className={'choice '+c.kind} onClick={()=>{setP(c);setSeen([]);setScreen('xray')}}><span><ShieldCheck/></span><div><b>{c.label}</b><small>{c.helper}</small></div><ArrowRight/></button>)}</div></main>}
 {screen==='xray'&&<main className="wide"><span className="eyebrow">MANIPULATION X-RAY</span><h2>Make invisible cues visible.</h2><p className="lead">Tap at least one signal to inspect it.</p><div className="xray">{s.xray.map((x,n)=><button key={x.t} className={seen.includes(n)?'open':''} onClick={()=>setSeen(v=>v.includes(n)?v.filter(z=>z!==n):[...v,n])}><small>0{n+1}</small><label>{x.s}</label><b>{x.t}</b><p>{seen.includes(n)?x.b:'Tap to inspect this signal.'}</p>{seen.includes(n)?<CheckCircle2/>:<Search/>}</button>)}</div><div className="stick"><span>{seen.length}/5 signals inspected</span><button className="primary" disabled={!seen.length} onClick={()=>s.shield?setScreen('shield'):save()}>Continue <ArrowRight/></button></div></main>}
 {screen==='shield'&&s.shield&&<main className="center"><span className="eyebrow">SHIELD MODE</span><h2>Turn support into a safer sequence.</h2><p className="lead">Educational guidance—not emergency support.</p><div className="shieldsteps">{s.shield.map((x,n)=><span key={x} className={n===shield?'active':n<shield?'done':''}>{n<shield?'✓':n+1}</span>)}</div><div className="panel shield"><Shield/><small>STEP {shield+1} / 5</small><h3>{s.shield[shield]!.split(' — ')[0]}</h3><p>{s.shield[shield]!.split(' — ')[1]}</p></div><div className="actions"><button disabled={shield===0} onClick={()=>setShield(shield-1)}>Back</button><button className="primary" onClick={()=>shield===4?save():setShield(shield+1)}>{shield===4?'Finish SHIELD':'Next step'} <ArrowRight/></button></div></main>}
 {screen==='complete'&&b&&p&&<main className="wide"><div className="success"><CheckCircle2/><span className="eyebrow">SCENARIO {i+1} COMPLETE</span><h2>The first click changed. So did the ripple.</h2></div><div className="compare">{(['reach','hostility','safety','trust'] as const).map(k=><div key={k}><span>{k}</span><strong>{mm(b)[k]} → {mm(p)[k]}</strong><small>safer direction</small></div>)}</div><div className="switch"><div><small>MIRROR</small><b>{b.label}</b></div><ArrowRight/><div><small>PEACE</small><b>{p.label}</b></div></div><button className="primary" onClick={next}>{i===2?'See my Digital Reflex Profile':'Continue to next scenario'} <ArrowRight/></button></main>}
 {screen==='results'&&<main className="wide results"><section><span className="eyebrow">DIGITAL REFLEX PROFILE</span><h2>{score>=85?'Strong peacebuilding reflexes':score>=65?'Developing strong reflexes':'Growing digital awareness'}</h2><p className="lead">A transparent learning summary based only on choices made inside this simulation.</p></section><div className="orb"><strong>{score}</strong><span>/100</span></div><div className="resultcards">{scenarios.map((x,n)=><div key={x.id}><small>Scenario {n+1}</small><b>{x.title}</b><strong>{results[n]||0}%</strong></div>)}</div><div className="callout"><Info/><p>This score is an in-session learning indicator—not a psychological diagnosis, validated impact estimate or pilot result. Submission evidence must come from a separate consented pilot.</p></div><footer><div><b>#EveryClickRipples</b><small>Every click has a consequence.</small></div><button onClick={reset}><RefreshCw/> Replay experience</button></footer></main>}
 </div>
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
