export type Locale='en'|'bn';
export type Metrics={reach:number;hostility:number;safety:number;trust:number};
export type ChoiceKind='risk'|'safe'|'neutral'|'support';
export type Skill='verify'|'manipulation'|'bystander'|'support'|'deescalate';

export type Choice={
  id:string;label:string;helper:string;kind:ChoiceKind;delta:Partial<Metrics>;
  score:number;title:string;body:string;
};

export type Scenario={
  id:string;title:string;tag:string;intro:string;post:string;prompt:string;
  choices:Choice[];peace:Choice[];xray:{t:string;s:string;b:string}[];
  shield?:string[];human?:string;skills?:Skill[];family?:string;
};

type Bi={en:string;bn:string};
type Mode='verify'|'bystander'|'privacy'|'deescalate'|'synthetic';

type Spec={
  key:string;mode:Mode;title:Bi;tag:Bi;post:Bi;human:Bi;
  safe:Bi;signal:Bi;skills:Skill[];
};

const b=(en:string,bn:string):Bi=>({en,bn});
const pick=(x:Bi,l:Locale)=>x[l];

const contexts:Record<Locale,string[]> = {
  en:['Campus group chat','Public social feed','Neighborhood/community chat'],
  bn:['ক্যাম্পাস গ্রুপ চ্যাট','পাবলিক সোশ্যাল ফিড','এলাকার/কমিউনিটি চ্যাট']
};

const specs:Spec[]=[
 {key:'voice-note',mode:'verify',title:b('The Forwarded Voice Note','ফরোয়ার্ড করা ভয়েস নোট'),tag:b('Rumor · Missing source','গুজব · উৎসহীন তথ্য'),post:b('A forwarded voice note says a local school is hiding a serious incident. The speaker is unnamed and no document or direct source is attached.','একটি ফরোয়ার্ড করা ভয়েস নোটে দাবি করা হচ্ছে স্থানীয় একটি স্কুল গুরুতর ঘটনা লুকাচ্ছে। বক্তার পরিচয় নেই, কোনো নথি বা সরাসরি উৎসও নেই।'),human:b('Parents begin calling students home. A fictional student misses an exam after her family believes the unverified warning.','অযাচাইকৃত সতর্কতা বিশ্বাস করে অভিভাবকেরা সন্তানদের বাসায় ডেকে নেয়। একটি কাল্পনিক শিক্ষার্থী পরীক্ষায় অংশ নিতে পারে না।'),safe:b('Trace who recorded it and look for a direct, accountable source.','কে রেকর্ড করেছে খুঁজুন এবং সরাসরি, দায়বদ্ধ উৎস যাচাই করুন।'),signal:b('Forwarded many times is not the same as verified.','অনেকবার ফরোয়ার্ড হওয়া মানেই যাচাইকৃত নয়।'),skills:['verify','manipulation']},
 {key:'edited-screenshot',mode:'verify',title:b('The Edited Screenshot','সম্পাদিত স্ক্রিনশট'),tag:b('Manipulated evidence · Context','বদলানো প্রমাণ · প্রেক্ষাপট'),post:b('A screenshot appears to show a teacher insulting students, but the top and bottom of the conversation are cropped out.','একটি স্ক্রিনশটে মনে হচ্ছে একজন শিক্ষক শিক্ষার্থীদের অপমান করেছেন, কিন্তু কথোপকথনের ওপর ও নিচের অংশ কাটা।'),human:b('The teacher is publicly named before the full exchange is checked, and their family receives abusive messages.','সম্পূর্ণ কথোপকথন যাচাইয়ের আগেই শিক্ষকের নাম ছড়িয়ে পড়ে এবং তার পরিবার অপমানজনক বার্তা পায়।'),safe:b('Ask for the full conversation and verify the original source.','পুরো কথোপকথন ও মূল উৎস যাচাই করুন।'),signal:b('A crop can turn a partial truth into a different story.','কাটা অংশ আংশিক সত্যকে অন্য গল্পে বদলে দিতে পারে।'),skills:['verify','manipulation']},
 {key:'scholarship',mode:'verify',title:b('The Scholarship Deadline','স্কলারশিপের শেষ সময়'),tag:b('Urgency · Scam signal','তাড়াহুড়া · প্রতারণার সংকেত'),post:b('A post promises a fully funded scholarship if students submit personal documents within two hours through an unfamiliar form.','একটি পোস্টে বলা হচ্ছে অপরিচিত ফর্মে দুই ঘণ্টার মধ্যে ব্যক্তিগত কাগজপত্র দিলে ফুল-ফান্ডেড স্কলারশিপ পাওয়া যাবে।'),human:b('A fictional applicant uploads identity documents to an unverified form and later loses control of where those files are shared.','একজন কাল্পনিক আবেদনকারী অযাচাইকৃত ফর্মে পরিচয়পত্র আপলোড করে এবং পরে ফাইলগুলো কোথায় ছড়িয়েছে তার নিয়ন্ত্রণ হারায়।'),safe:b('Verify the scholarship on the institution’s official site before submitting anything.','কোনো তথ্য দেওয়ার আগে প্রতিষ্ঠানের অফিসিয়াল সাইটে স্কলারশিপটি যাচাই করুন।'),signal:b('Urgency plus sensitive-data requests should slow you down.','তাড়াহুড়া ও সংবেদনশীল তথ্য চাওয়া দেখলে থামা উচিত।'),skills:['verify','manipulation']},
 {key:'relief-rumor',mode:'deescalate',title:b('The Relief Rumor','ত্রাণ নিয়ে গুজব'),tag:b('Crisis rumor · Community trust','সংকটের গুজব · সামাজিক আস্থা'),post:b('A post claims one neighborhood is secretly taking all relief supplies. It shows no distribution list, date or organizer statement.','একটি পোস্টে দাবি করা হচ্ছে একটি এলাকা গোপনে সব ত্রাণ নিয়ে নিচ্ছে। কোনো তালিকা, তারিখ বা আয়োজকের বক্তব্য নেই।'),human:b('Volunteers at a fictional relief point are confronted and distribution pauses while families wait for supplies.','একটি কাল্পনিক ত্রাণকেন্দ্রে স্বেচ্ছাসেবকদের ঘিরে ধরা হয়; বিতরণ বন্ধ হয়ে যায়, পরিবারগুলো অপেক্ষায় থাকে।'),safe:b('Check the organizer’s verified distribution information and correct the claim without blaming a group.','আয়োজকের যাচাইকৃত তথ্য দেখুন এবং কোনো গোষ্ঠীকে দোষ না দিয়ে ভুল দাবি সংশোধন করুন।'),signal:b('Scarcity and group blame can rapidly increase tension.','সংকট ও গোষ্ঠীকে দোষারোপ দ্রুত উত্তেজনা বাড়াতে পারে।'),skills:['verify','deescalate']},
 {key:'exam-leak',mode:'verify',title:b('The “Leaked” Exam','“ফাঁস” হওয়া পরীক্ষা'),tag:b('Virality · False certainty','ভাইরাল দাবি · মিথ্যা নিশ্চয়তা'),post:b('A file labeled “tomorrow’s exam question” spreads through student chats. Nobody can identify the original uploader.','“আগামীকালের পরীক্ষার প্রশ্ন” নামে একটি ফাইল শিক্ষার্থীদের গ্রুপে ছড়ায়। মূল আপলোডারকে কেউ চেনে না।'),human:b('A fictional student skips revision to follow the fake leak and faces disciplinary suspicion when the file spreads from their account.','একজন কাল্পনিক শিক্ষার্থী ভুয়া ফাঁসের ওপর ভরসা করে পড়া বাদ দেয় এবং তার অ্যাকাউন্ট থেকে ছড়ানোর কারণে শাস্তিমূলক সন্দেহে পড়ে।'),safe:b('Do not redistribute it; verify through official academic channels.','এটি ছড়াবেন না; অফিসিয়াল একাডেমিক চ্যানেলে যাচাই করুন।'),signal:b('A confident filename is not evidence of authenticity.','নিশ্চিত শিরোনাম সত্যতার প্রমাণ নয়।'),skills:['verify','manipulation']},
 {key:'campus-fight',mode:'deescalate',title:b('The 12-Second Fight Clip','১২ সেকেন্ডের মারামারির ক্লিপ'),tag:b('Cropped video · Escalation','কাটা ভিডিও · উত্তেজনা'),post:b('A short clip shows two students fighting. A caption assigns blame to an entire student group, but the clip starts after the conflict began.','ছোট একটি ক্লিপে দুই শিক্ষার্থীর মারামারি দেখা যাচ্ছে। ক্যাপশনে পুরো একটি ছাত্রগোষ্ঠীকে দায়ী করা হয়েছে, কিন্তু ভিডিওটি ঘটনার মাঝখান থেকে শুরু।'),human:b('Students who were not involved receive threats because they share the same group identity used in the caption.','ঘটনায় জড়িত না থাকা শিক্ষার্থীরাও শুধু একই পরিচয়ের কারণে হুমকি পায়।'),safe:b('Find the full context and avoid turning an individual incident into group blame.','পূর্ণ প্রেক্ষাপট খুঁজুন এবং ব্যক্তিগত ঘটনাকে গোষ্ঠীগত দোষে পরিণত করবেন না।'),signal:b('Identity framing can make one incident feel like proof about everyone.','পরিচয়ভিত্তিক ফ্রেম একটি ঘটনাকে পুরো গোষ্ঠীর প্রমাণ মনে করাতে পারে।'),skills:['verify','deescalate']},
 {key:'health-rumor',mode:'verify',title:b('The Miracle Health Post','অলৌকিক চিকিৎসার পোস্ট'),tag:b('Health misinformation · Authority','স্বাস্থ্য ভুলতথ্য · ভুয়া কর্তৃত্ব'),post:b('A viral card claims a common home remedy can replace professional treatment and uses a fake-looking medical logo.','একটি ভাইরাল কার্ডে দাবি করা হচ্ছে ঘরোয়া উপায় পেশাদার চিকিৎসার বিকল্প; সাথে সন্দেহজনক মেডিকেল লোগো।'),human:b('A fictional family delays seeking qualified help because the post looked authoritative.','পোস্টটি বিশ্বাসযোগ্য মনে হওয়ায় একটি কাল্পনিক পরিবার যোগ্য চিকিৎসা নিতে দেরি করে।'),safe:b('Check qualified health guidance and the original institution before acting or sharing.','কাজ বা শেয়ার করার আগে যোগ্য স্বাস্থ্য নির্দেশনা ও মূল প্রতিষ্ঠান যাচাই করুন।'),signal:b('Logos and medical language can imitate authority.','লোগো ও মেডিকেল ভাষা ভুয়া কর্তৃত্ব তৈরি করতে পারে।'),skills:['verify','manipulation']},
 {key:'job-scam',mode:'privacy',title:b('The Urgent Job Offer','জরুরি চাকরির অফার'),tag:b('Impersonation · Personal data','ছদ্মবেশ · ব্যক্তিগত তথ্য'),post:b('A recruiter account offers an interview today if you send NID details, a selfie and a payment screenshot first.','একটি রিক্রুটার অ্যাকাউন্ট আজই ইন্টারভিউয়ের প্রতিশ্রুতি দিয়ে আগে NID তথ্য, সেলফি ও পেমেন্ট স্ক্রিনশট চাইছে।'),human:b('A fictional graduate sends the files and later discovers a fake account using their identity to contact others.','একজন কাল্পনিক গ্র্যাজুয়েট ফাইল পাঠিয়ে পরে দেখে তার পরিচয় ব্যবহার করে অন্যদের সাথে যোগাযোগ করা হচ্ছে।'),safe:b('Verify the employer independently and never send sensitive identity files through an unverified account.','নিয়োগদাতাকে আলাদাভাবে যাচাই করুন এবং অযাচাইকৃত অ্যাকাউন্টে সংবেদনশীল পরিচয়পত্র পাঠাবেন না।'),signal:b('High reward + urgency + sensitive data is a high-risk combination.','বড় লাভ + তাড়াহুড়া + সংবেদনশীল তথ্য = উচ্চ ঝুঁকি।'),skills:['verify','support']},
 {key:'impersonation',mode:'privacy',title:b('The Copycat Account','নকল অ্যাকাউন্ট'),tag:b('Impersonation · Reputation','ছদ্মবেশ · সুনাম'),post:b('A new account copies a student’s name and photo, then posts offensive comments that look like they came from the student.','নতুন একটি অ্যাকাউন্ট একজন শিক্ষার্থীর নাম-ছবি কপি করে আপত্তিকর মন্তব্য করছে, যেন সেগুলো ওই শিক্ষার্থী করেছে।'),human:b('Classmates distance themselves from the fictional student before anyone checks whether the account is real.','অ্যাকাউন্টটি আসল কিনা যাচাইয়ের আগেই সহপাঠীরা কাল্পনিক শিক্ষার্থীটির কাছ থেকে দূরে সরে যায়।'),safe:b('Preserve the minimum evidence, report impersonation and verify the real account before repeating the content.','ন্যূনতম প্রয়োজনীয় প্রমাণ রাখুন, ছদ্মবেশী অ্যাকাউন্ট রিপোর্ট করুন এবং কনটেন্ট ছড়ানোর আগে আসল অ্যাকাউন্ট যাচাই করুন।'),signal:b('Identity can be copied faster than reputation can be repaired.','পরিচয় কপি করা যত দ্রুত, সুনাম ফিরিয়ে আনা তত সহজ নয়।'),skills:['bystander','support']},
 {key:'deepfake-endorsement',mode:'synthetic',title:b('The Fake Endorsement','ভুয়া সমর্থনের ভিডিও'),tag:b('Synthetic media · Verification','সিনথেটিক মিডিয়া · যাচাই'),post:b('A polished clip appears to show a familiar local figure promoting a financial offer. The lip movement feels slightly unnatural and no original post is found.','একটি ঝকঝকে ভিডিওতে পরিচিত স্থানীয় ব্যক্তিকে আর্থিক অফার প্রচার করতে দেখা যায়। ঠোঁটের নড়াচড়া অস্বাভাবিক, মূল পোস্টও পাওয়া যাচ্ছে না।'),human:b('A fictional viewer transfers money because the familiar face makes the offer feel safe.','পরিচিত মুখ দেখে অফারটি নিরাপদ মনে হওয়ায় একজন কাল্পনিক দর্শক টাকা পাঠিয়ে দেয়।'),safe:b('Find the original verified channel and independently confirm the offer.','মূল যাচাইকৃত চ্যানেল খুঁজুন এবং অফারটি আলাদাভাবে নিশ্চিত করুন।'),signal:b('Familiar faces can create trust even when the media is synthetic.','পরিচিত মুখ সিনথেটিক মিডিয়াকেও বিশ্বাসযোগ্য মনে করাতে পারে।'),skills:['verify','manipulation']},
 {key:'private-photo',mode:'privacy',title:b('The Private Photo','ব্যক্তিগত ছবি'),tag:b('Consent · Recirculation','সম্মতি · পুনরায় ছড়ানো'),post:b('Someone drops a private-looking photo of a fictional student into a chat and people start asking for the “full set”.','একটি চ্যাটে কাল্পনিক শিক্ষার্থীর ব্যক্তিগত মনে হওয়া ছবি দেওয়া হয় এবং অনেকে “পুরো সেট” চাইতে থাকে।'),human:b('The student stops attending class for several days because they fear every phone in the room may contain the image.','ছবিটি সবার ফোনে থাকতে পারে—এই ভয়ে শিক্ষার্থীটি কয়েকদিন ক্লাসে যায় না।'),safe:b('Do not save or forward it; support the person and report the sharing pathway.','ছবি সেভ বা ফরোয়ার্ড করবেন না; ব্যক্তিকে সহায়তা করুন এবং শেয়ারিং পথ রিপোর্ট করুন।'),signal:b('“Just forwarding” extends the loss of control.','“শুধু ফরোয়ার্ড” করাও নিয়ন্ত্রণ হারানোকে বাড়ায়।'),skills:['bystander','support']},
 {key:'doxxing',mode:'privacy',title:b('The Shared Address','শেয়ার করা ঠিকানা'),tag:b('Doxxing · Safety','ডক্সিং · নিরাপত্তা'),post:b('An angry thread includes a screenshot with a fictional person’s home area and phone number visible.','রাগান্বিত একটি থ্রেডে কাল্পনিক ব্যক্তির বাসার এলাকা ও ফোন নম্বর দেখা যায় এমন স্ক্রিনশট দেওয়া হয়েছে।'),human:b('Strangers begin calling the person and a family member becomes afraid to leave home alone.','অপরিচিতরা ফোন করতে শুরু করে এবং পরিবারের একজন একা বাইরে যেতে ভয় পায়।'),safe:b('Do not recirculate the personal data; report it and warn the person privately.','ব্যক্তিগত তথ্য আর ছড়াবেন না; রিপোর্ট করুন এবং ব্যক্তিটিকে ব্যক্তিগতভাবে সতর্ক করুন।'),signal:b('Public anger plus location data can create offline safety risk.','পাবলিক রাগের সাথে লোকেশন তথ্য বাস্তব নিরাপত্তা ঝুঁকি তৈরি করতে পারে।'),skills:['bystander','support','deescalate']},
 {key:'pile-on',mode:'bystander',title:b('The Group Chat Pile-On','গ্রুপ চ্যাটে দলবদ্ধ অপমান'),tag:b('Cyberbullying · Bystander','সাইবারবুলিং · দর্শকের ভূমিকা'),post:b('One awkward message from a fictional student is screenshotted, reposted and turned into a running joke across chats.','একজন কাল্পনিক শিক্ষার্থীর অস্বস্তিকর একটি মেসেজ স্ক্রিনশট করে বিভিন্ন চ্যাটে মজা হিসেবে ছড়ানো হচ্ছে।'),human:b('The student leaves the class group and stops asking classmates for help with coursework.','শিক্ষার্থীটি ক্লাস গ্রুপ ছেড়ে দেয় এবং পড়াশোনার সাহায্য চাওয়া বন্ধ করে।'),safe:b('Check on the target, stop recirculating the screenshot and set a calm boundary in the group.','আক্রান্ত ব্যক্তির খোঁজ নিন, স্ক্রিনশট ছড়ানো বন্ধ করুন এবং গ্রুপে শান্তভাবে সীমা নির্ধারণ করুন।'),signal:b('Every laugh reaction tells the crowd the behavior is acceptable.','প্রতিটি হাসির রিঅ্যাক্ট ভিড়কে জানায় আচরণটি গ্রহণযোগ্য।'),skills:['bystander','support']},
 {key:'appearance-meme',mode:'bystander',title:b('The Appearance Meme','চেহারা নিয়ে মিম'),tag:b('Mockery · Social proof','উপহাস · সামাজিক অনুমোদন'),post:b('A student’s event photo is edited into a meme about their body and hundreds of reaction emojis appear underneath.','একজন শিক্ষার্থীর অনুষ্ঠানের ছবি এডিট করে শরীর নিয়ে মিম বানানো হয়েছে এবং নিচে শত শত রিঅ্যাক্ট।'),human:b('The fictional student deletes their public photos and avoids the next campus event.','কাল্পনিক শিক্ষার্থীটি নিজের পাবলিক ছবি মুছে দেয় এবং পরের ক্যাম্পাস অনুষ্ঠান এড়িয়ে চলে।'),safe:b('Do not reward the pile-on; support the target and report abusive edits.','দলবদ্ধ অপমানকে রিঅ্যাক্ট দিয়ে পুরস্কৃত করবেন না; আক্রান্ত ব্যক্তিকে সহায়তা ও অপমানজনক এডিট রিপোর্ট করুন।'),signal:b('Large reaction counts can normalize cruelty.','অনেক রিঅ্যাক্ট নিষ্ঠুরতাকে স্বাভাবিক মনে করাতে পারে।'),skills:['bystander','support']},
 {key:'result-shame',mode:'bystander',title:b('The Result Screenshot','রেজাল্টের স্ক্রিনশট'),tag:b('Public shaming · Privacy','পাবলিক অপমান · গোপনীয়তা'),post:b('A private exam-result screenshot is posted to mock a fictional student for a low mark.','কম নম্বর পাওয়ায় একটি কাল্পনিক শিক্ষার্থীকে উপহাস করতে ব্যক্তিগত রেজাল্টের স্ক্রিনশট পোস্ট করা হয়েছে।'),human:b('The student stops participating in study groups and tells a friend they feel watched whenever grades are discussed.','শিক্ষার্থীটি স্টাডি গ্রুপে অংশ নেওয়া বন্ধ করে এবং ফল নিয়ে কথা উঠলে নিজেকে নজরবন্দি মনে করে।'),safe:b('Remove the private result from circulation and challenge the shaming without attacking others.','ব্যক্তিগত ফল ছড়ানো বন্ধ করুন এবং কাউকে আক্রমণ না করে অপমানের বিরোধিতা করুন।'),signal:b('Humiliation becomes harder to escape when private information is searchable.','ব্যক্তিগত তথ্য ছড়িয়ে পড়লে অপমান থেকে বের হওয়া কঠিন হয়।'),skills:['bystander','support']},
 {key:'disability-mock',mode:'bystander',title:b('The Accessibility Joke','প্রতিবন্ধকতা নিয়ে “মজা”'),tag:b('Ableism · Exclusion','প্রতিবন্ধীবিদ্বেষ · বর্জন'),post:b('A clip of a fictional student using an accessibility aid is reposted with mocking captions.','সহায়ক ডিভাইস ব্যবহার করা এক কাল্পনিক শিক্ষার্থীর ভিডিও ব্যঙ্গাত্মক ক্যাপশন দিয়ে ছড়ানো হচ্ছে।'),human:b('The student stops using the aid publicly for fear of being recorded again, making daily movement harder.','আবার ভিডিও হওয়ার ভয়ে শিক্ষার্থীটি প্রকাশ্যে সহায়ক ডিভাইস ব্যবহার কমিয়ে দেয়, ফলে দৈনন্দিন চলাচল কঠিন হয়।'),safe:b('Do not amplify the clip; support the student and challenge the demeaning frame.','ক্লিপটি ছড়াবেন না; শিক্ষার্থীকে সহায়তা করুন এবং অপমানজনক ফ্রেমের বিরোধিতা করুন।'),signal:b('A “joke” can pressure someone to hide a legitimate need.','“মজা” কাউকে প্রয়োজনীয় সহায়তা লুকাতে বাধ্য করতে পারে।'),skills:['bystander','support']},
 {key:'gendered-abuse',mode:'bystander',title:b('The Sexualized Replies','যৌন ইঙ্গিতপূর্ণ মন্তব্য'),tag:b('Gendered harassment · Escalation','লিঙ্গভিত্তিক হয়রানি · উত্তেজনা'),post:b('A fictional young woman posts an opinion. Replies shift from disagreement to sexualized insults and threatening messages.','একজন কাল্পনিক তরুণী মতামত পোস্ট করে। মন্তব্য মতভেদ থেকে যৌন ইঙ্গিতপূর্ণ অপমান ও হুমকিতে চলে যায়।'),human:b('She changes her route home and stops posting publicly because online threats feel capable of moving offline.','অনলাইন হুমকি বাস্তবে চলে আসতে পারে মনে হওয়ায় সে বাসায় ফেরার পথ বদলায় এবং পাবলিক পোস্ট বন্ধ করে।'),safe:b('Support her privately, preserve only necessary evidence, report threats and avoid recirculating abuse.','ব্যক্তিগতভাবে সহায়তা করুন, প্রয়োজনীয় প্রমাণ রাখুন, হুমকি রিপোর্ট করুন এবং অপমানজনক কনটেন্ট আর ছড়াবেন না।'),signal:b('Online threats can change offline behavior even before physical harm occurs.','শারীরিক ক্ষতি হওয়ার আগেই অনলাইন হুমকি বাস্তব জীবনের আচরণ বদলে দিতে পারে।'),skills:['bystander','support','deescalate']},
 {key:'relationship-rumor',mode:'bystander',title:b('The Relationship Rumor','সম্পর্ক নিয়ে গুজব'),tag:b('Rumor · Reputation','গুজব · সুনাম'),post:b('An anonymous post claims two fictional students are secretly in a relationship and tags their classmates for “proof”.','একটি বেনামী পোস্টে দুই কাল্পনিক শিক্ষার্থীর গোপন সম্পর্কের দাবি করে সহপাঠীদের “প্রমাণ” দিতে ট্যাগ করা হয়েছে।'),human:b('One student faces intense family conflict after classmates forward the rumor outside the campus group.','সহপাঠীরা গুজবটি ক্যাম্পাসের বাইরে পাঠানোর পর একজন শিক্ষার্থী পরিবারে তীব্র দ্বন্দ্বের মুখে পড়ে।'),safe:b('Do not investigate or spread private-life rumors; remove identifying details and support the people targeted.','ব্যক্তিগত জীবন নিয়ে গুজব অনুসন্ধান বা ছড়াবেন না; পরিচয় শনাক্তকারী তথ্য সরিয়ে আক্রান্তদের সহায়তা করুন।'),signal:b('Curiosity can become surveillance when a crowd searches for “proof”.','ভিড় “প্রমাণ” খুঁজতে গেলে কৌতূহল নজরদারিতে পরিণত হতে পারে।'),skills:['bystander','support']},
 {key:'anonymous-confession',mode:'bystander',title:b('The Anonymous Confession Page','বেনামী কনফেশন পেজ'),tag:b('Anonymity · Targeting','বেনামিতা · টার্গেটিং'),post:b('An anonymous campus page posts a humiliating allegation about a fictional student with enough details for everyone to identify them.','একটি বেনামী ক্যাম্পাস পেজ কাল্পনিক শিক্ষার্থী সম্পর্কে অপমানজনক অভিযোগ পোস্ট করে, এমন তথ্যসহ যাতে সবাই তাকে চিনতে পারে।'),human:b('The student receives hundreds of messages but has no clear way to confront the anonymous source.','শিক্ষার্থীটি শত শত বার্তা পায়, কিন্তু বেনামী উৎসের জবাব দেওয়ার পরিষ্কার সুযোগ নেই।'),safe:b('Do not pile on; report targeted harassment and avoid repeating identifying details.','দলবদ্ধ আক্রমণে যোগ দেবেন না; টার্গেটেড হয়রানি রিপোর্ট করুন এবং পরিচয় শনাক্তকারী তথ্য পুনরাবৃত্তি করবেন না।'),signal:b('Anonymity can remove accountability while keeping the target fully exposed.','বেনামিতা পোস্টদাতার দায় কমায়, কিন্তু টার্গেটকে পুরোপুরি উন্মুক্ত রাখে।'),skills:['bystander','support']},
 {key:'festival-rumor',mode:'deescalate',title:b('The Festival Rumor','উৎসব নিয়ে গুজব'),tag:b('Identity rumor · Community tension','পরিচয়ভিত্তিক গুজব · সামাজিক উত্তেজনা'),post:b('A post claims a fictional minority community deliberately disrespected a local festival. No direct witness or original media is shown.','একটি পোস্টে দাবি করা হচ্ছে কাল্পনিক সংখ্যালঘু সম্প্রদায় ইচ্ছাকৃতভাবে স্থানীয় উৎসবকে অসম্মান করেছে। কোনো সরাসরি সাক্ষী বা মূল মিডিয়া নেই।'),human:b('A small business run by an uninvolved family receives boycott calls simply because of the family’s identity.','ঘটনায় জড়িত না থাকা একটি পরিবারের ছোট ব্যবসা শুধু পরিচয়ের কারণে বয়কটের ডাক পায়।'),safe:b('Separate the specific claim from group identity and verify direct evidence before responding.','নির্দিষ্ট দাবিকে গোষ্ঠীর পরিচয় থেকে আলাদা করুন এবং প্রতিক্রিয়ার আগে সরাসরি প্রমাণ যাচাই করুন।'),signal:b('Collective blame can punish people who had nothing to do with an event.','সমষ্টিগত দোষ এমন মানুষকেও শাস্তি দিতে পারে যারা ঘটনার সাথে জড়িত নয়।'),skills:['verify','deescalate']},
 {key:'vandalism-blame',mode:'deescalate',title:b('The Vandalism Blame','ভাঙচুরের দায়'),tag:b('Unverified blame · Communal risk','অযাচাইকৃত দোষ · সাম্প্রদায়িক ঝুঁকি'),post:b('A damaged sign is photographed and a caption immediately blames a named fictional community, without showing who caused it.','ক্ষতিগ্রস্ত একটি সাইনবোর্ডের ছবি দিয়ে কে করেছে না দেখিয়েই কাল্পনিক একটি সম্প্রদায়কে দায়ী করা হয়েছে।'),human:b('Young people from that community cancel an evening event after hostile comments mention confronting them.','হুমকিমূলক মন্তব্যে মুখোমুখি হওয়ার কথা আসায় ওই সম্প্রদায়ের তরুণরা সন্ধ্যার অনুষ্ঠান বাতিল করে।'),safe:b('Do not convert unknown responsibility into group blame; wait for accountable evidence.','অজানা দায়কে গোষ্ঠীগত দোষে পরিণত করবেন না; দায়বদ্ধ প্রমাণের অপেক্ষা করুন।'),signal:b('A photo can prove damage happened without proving who caused it.','ছবি ক্ষতি দেখাতে পারে, কিন্তু কে করেছে তা প্রমাণ করে না।'),skills:['verify','deescalate']},
 {key:'protest-clip',mode:'verify',title:b('The Old Protest Clip','পুরোনো প্রতিবাদের ক্লিপ'),tag:b('Old media · False context','পুরোনো মিডিয়া · ভুল প্রেক্ষাপট'),post:b('A dramatic crowd video is posted as if it happened today, but signs in the background suggest it may be from an older event.','নাটকীয় জনসমাবেশের ভিডিও আজকের বলে পোস্ট করা হয়েছে, কিন্তু পেছনের সাইন দেখে মনে হচ্ছে এটি পুরোনো ঘটনার।'),human:b('A fictional shop owner closes early after believing the video shows unrest happening nearby right now.','ভিডিওটি কাছাকাছি বর্তমান অস্থিরতা দেখাচ্ছে মনে করে একজন কাল্পনিক দোকানদার আগেই দোকান বন্ধ করে।'),safe:b('Check the earliest upload, date clues and reliable local reporting before sharing.','শেয়ার করার আগে প্রথম আপলোড, তারিখের সংকেত ও নির্ভরযোগ্য স্থানীয় প্রতিবেদন যাচাই করুন।'),signal:b('Real footage can still be misinformation when time or place is wrong.','আসল ফুটেজও সময় বা স্থান ভুল হলে ভুলতথ্য হতে পারে।'),skills:['verify','manipulation']},
 {key:'outsider-stereotype',mode:'deescalate',title:b('The Outsider Story','বাইরের মানুষের গল্প'),tag:b('Missing voice · Stereotype','অনুপস্থিত কণ্ঠ · স্টেরিওটাইপ'),post:b('A popular thread explains “what a fictional minority community really wants” but quotes nobody from that community and links no primary source.','জনপ্রিয় একটি থ্রেডে “কাল্পনিক সংখ্যালঘু সম্প্রদায় আসলে কী চায়” বলা হচ্ছে, কিন্তু সেই সম্প্রদায়ের কারও বক্তব্য বা মূল উৎস নেই।'),human:b('A fictional community volunteer is flooded with demands to defend views they never expressed.','একজন কাল্পনিক কমিউনিটি স্বেচ্ছাসেবক এমন মতামতের জবাব দিতে চাপ পায় যা সে কখনো বলেনি।'),safe:b('Seek relevant first-person sources without making one person represent everyone.','একজনকে পুরো গোষ্ঠীর প্রতিনিধি না বানিয়ে প্রাসঙ্গিক প্রথম-ব্যক্তির উৎস খুঁজুন।'),signal:b('A story can sound complete while excluding the people being described.','যাদের নিয়ে বলা হচ্ছে তাদের বাদ দিয়েও গল্প সম্পূর্ণ মনে হতে পারে।'),skills:['verify','deescalate']},
 {key:'quote-card',mode:'verify',title:b('The Quote Card','কোট কার্ড'),tag:b('Fabricated quote · Authority','বানানো উদ্ধৃতি · কর্তৃত্ব'),post:b('A polished graphic attributes an inflammatory quote to a fictional public speaker, but no recording, transcript or original post can be found.','ঝকঝকে গ্রাফিকে কাল্পনিক বক্তার নামে উত্তেজক উদ্ধৃতি দেওয়া হয়েছে, কিন্তু কোনো রেকর্ডিং, ট্রান্সক্রিপ্ট বা মূল পোস্ট নেই।'),human:b('People direct abuse at the speaker’s workplace and colleagues even though the quote cannot be verified.','উদ্ধৃতি যাচাই করা না গেলেও মানুষ বক্তার কর্মস্থল ও সহকর্মীদের দিকে অপমান ছুড়ে দেয়।'),safe:b('Search for the original speech/post and label the quote unverified until found.','মূল বক্তব্য/পোস্ট খুঁজুন; না পাওয়া পর্যন্ত উদ্ধৃতিকে অযাচাইকৃত বলুন।'),signal:b('Professional design can make invented text feel sourced.','পেশাদার ডিজাইন বানানো লেখাকেও উৎসসমৃদ্ধ মনে করাতে পারে।'),skills:['verify','manipulation']},
 {key:'rage-headline',mode:'deescalate',title:b('The Rage-Bait Headline','রাগ উসকে দেওয়া শিরোনাম'),tag:b('Engagement bait · Polarization','এনগেজমেন্ট বেইট · মেরুকরণ'),post:b('A headline says “THIS GROUP HATES YOU” while the linked article contains a much narrower, uncertain claim.','শিরোনামে লেখা “এই গোষ্ঠী আপনাকে ঘৃণা করে”, কিন্তু ভেতরের লেখায় অনেক সীমিত ও অনিশ্চিত দাবি।'),human:b('Friends who usually cooperate begin attacking each other in comments based on the headline alone.','শুধু শিরোনাম দেখে সাধারণত সহযোগী বন্ধুরা মন্তব্যে একে অন্যকে আক্রমণ শুরু করে।'),safe:b('Read beyond the headline and restate only what the evidence actually supports.','শিরোনামের বাইরে পড়ুন এবং প্রমাণ যতটুকু সমর্থন করে ততটুকুই বলুন।'),signal:b('Anger is an engagement strategy; strong emotion is a cue to slow down.','রাগ এনগেজমেন্ট কৌশল হতে পারে; তীব্র আবেগ থামার সংকেত।'),skills:['verify','manipulation','deescalate']},
 {key:'dm-screenshot',mode:'privacy',title:b('The Private DM Screenshot','ব্যক্তিগত DM-এর স্ক্রিনশট'),tag:b('Privacy · Context collapse','গোপনীয়তা · প্রেক্ষাপট হারানো'),post:b('A private disagreement is screenshotted and posted publicly with names visible so strangers can “decide who is right”.','ব্যক্তিগত মতবিরোধের স্ক্রিনশট নামসহ পাবলিক করা হয়েছে যাতে অপরিচিতরা “কে ঠিক” সিদ্ধান্ত দেয়।'),human:b('One fictional participant receives messages from strangers long after the original disagreement was resolved privately.','মূল বিরোধ ব্যক্তিগতভাবে মিটে যাওয়ার পরও একজন কাল্পনিক অংশগ্রহণকারী অপরিচিতদের বার্তা পেতে থাকে।'),safe:b('Keep private conflict private where safe; redact identifiers and avoid recruiting a crowd.','নিরাপদ হলে ব্যক্তিগত বিরোধ ব্যক্তিগত রাখুন; পরিচয় মুছে দিন এবং ভিড় ডেকে আনবেন না।'),signal:b('Public audiences can keep a conflict alive after the people involved move on.','পাবলিক দর্শক জড়িতদের বিরোধ মিটে যাওয়ার পরও তা বাঁচিয়ে রাখতে পারে।'),skills:['bystander','support','deescalate']},
 {key:'poll',mode:'verify',title:b('The Manipulated Poll','বদলানো জরিপ'),tag:b('Bad data · Social proof','খারাপ ডেটা · সামাজিক প্রমাণ'),post:b('A graphic says “92% of students agree” but gives no sample size, question wording or link to the survey.','একটি গ্রাফিকে লেখা “৯২% শিক্ষার্থী একমত”, কিন্তু sample size, প্রশ্ন বা জরিপের লিংক নেই।'),human:b('A student organization changes a plan because members think almost everyone supports the claim, even though the poll cannot be checked.','জরিপ যাচাই করা না গেলেও প্রায় সবাই সমর্থন করে মনে করে একটি ছাত্রসংগঠন পরিকল্পনা বদলে ফেলে।'),safe:b('Ask for sample size, wording, method and the original dataset before treating the number as evidence.','সংখ্যাকে প্রমাণ ধরার আগে sample size, প্রশ্ন, পদ্ধতি ও মূল ডেটা চাইুন।'),signal:b('A percentage without method can manufacture consensus.','পদ্ধতি ছাড়া শতাংশ কৃত্রিম ঐকমত্য তৈরি করতে পারে।'),skills:['verify','manipulation']},
 {key:'ai-image',mode:'synthetic',title:b('The AI-Generated Disaster Image','AI-তৈরি দুর্যোগের ছবি'),tag:b('Synthetic image · Crisis','সিনথেটিক ছবি · সংকট'),post:b('A shocking flood image spreads with a donation request. Strange text and repeated details suggest the image may be generated.','ভয়াবহ বন্যার ছবি দিয়ে অনুদান চাওয়া হচ্ছে। অদ্ভুত লেখা ও পুনরাবৃত্ত ডিটেইল দেখে ছবিটি তৈরি করা হতে পারে মনে হচ্ছে।'),human:b('Donations are diverted away from verified relief channels because the fictional image triggers urgency.','কাল্পনিক ছবির তাড়াহুড়ায় অনুদান যাচাইকৃত ত্রাণ চ্যানেল থেকে অন্যদিকে চলে যায়।'),safe:b('Verify the image, organizer and donation channel independently before sharing or paying.','শেয়ার বা টাকা দেওয়ার আগে ছবি, আয়োজক ও অনুদান চ্যানেল আলাদাভাবে যাচাই করুন।'),signal:b('Visual realism is no longer proof that an event happened as shown.','ছবি বাস্তব দেখালেই ঘটনা সেভাবে ঘটেছে—এটা আর নিশ্চিত নয়।'),skills:['verify','manipulation']},
 {key:'edited-audio',mode:'synthetic',title:b('The Cut Audio Clip','কাটা অডিও ক্লিপ'),tag:b('Audio edit · Missing context','অডিও এডিট · অনুপস্থিত প্রেক্ষাপট'),post:b('A 14-second audio clip appears to capture a fictional organizer saying something offensive, but there is no full recording.','১৪ সেকেন্ডের অডিওতে কাল্পনিক আয়োজককে আপত্তিকর কথা বলতে শোনা যাচ্ছে, কিন্তু পুরো রেকর্ডিং নেই।'),human:b('A community meeting is cancelled after threats target the organizer before anyone checks whether the audio was edited.','অডিও এডিট কিনা যাচাইয়ের আগেই আয়োজককে হুমকি দেওয়া হয় এবং কমিউনিটি মিটিং বাতিল হয়।'),safe:b('Find the full recording and a direct source before assigning meaning to a short clip.','ছোট ক্লিপের অর্থ নির্ধারণের আগে পুরো রেকর্ডিং ও সরাসরি উৎস খুঁজুন।'),signal:b('Audio can be cut, rearranged or synthesized just like images and video.','ছবি-ভিডিওর মতো অডিওও কাটা, সাজানো বা তৈরি করা যায়।'),skills:['verify','manipulation','deescalate']},
 {key:'fake-alert',mode:'verify',title:b('The Fake Emergency Alert','ভুয়া জরুরি সতর্কতা'),tag:b('False alert · Panic','ভুয়া সতর্কতা · আতঙ্ক'),post:b('A screenshot designed like an official emergency notice tells everyone to avoid a large area, but no official channel carries it.','অফিসিয়াল জরুরি নোটিশের মতো দেখতে স্ক্রিনশট সবাইকে বড় একটি এলাকা এড়িয়ে চলতে বলছে, কিন্তু কোনো অফিসিয়াল চ্যানেলে নেই।'),human:b('A fictional caregiver misses a hospital appointment after changing plans around the false alert.','ভুয়া সতর্কতা মেনে পরিকল্পনা বদলানোর কারণে একজন কাল্পনিক অভিভাবক হাসপাতালের অ্যাপয়েন্টমেন্ট মিস করেন।'),safe:b('Check the relevant official emergency channel before forwarding the alert.','সতর্কতা ফরোয়ার্ড করার আগে সংশ্লিষ্ট অফিসিয়াল জরুরি চ্যানেল যাচাই করুন।'),signal:b('Visual imitation of official notices can trigger fast compliance.','অফিসিয়াল নোটিশের নকল দ্রুত মানুষকে মানতে বাধ্য করতে পারে।'),skills:['verify','manipulation']},
 {key:'crowd-accusation',mode:'deescalate',title:b('The Crowd Accusation','ভিড়ের অভিযোগ'),tag:b('Unverified accusation · Mob logic','অযাচাইকৃত অভিযোগ · ভিড়ের যুক্তি'),post:b('A post names a fictional person as responsible for a local problem because “everyone in the comments knows it”. No source is provided.','একটি পোস্টে বলা হচ্ছে স্থানীয় সমস্যার জন্য কাল্পনিক একজন ব্যক্তি দায়ী, কারণ “কমেন্টে সবাই জানে”। কোনো উৎস নেই।'),human:b('The person’s workplace receives calls demanding punishment before any evidence is checked.','কোনো প্রমাণ যাচাইয়ের আগেই ব্যক্তির কর্মস্থলে শাস্তির দাবিতে ফোন আসতে থাকে।'),safe:b('Do not convert comment consensus into evidence; ask for accountable sources and avoid naming an unverified target.','কমেন্টের ঐকমত্যকে প্রমাণ বানাবেন না; দায়বদ্ধ উৎস চাইুন এবং অযাচাইকৃত কাউকে নাম ধরে টার্গেট করবেন না।'),signal:b('Crowd certainty can feel like proof even when everyone is repeating the same unsupported claim.','একই অযাচাইকৃত দাবি সবাই পুনরাবৃত্তি করলে ভিড়ের নিশ্চয়তা প্রমাণ মনে হতে পারে।'),skills:['verify','deescalate']},
 {key:'victim-blame',mode:'bystander',title:b('The “Why Did They Post It?” Thread','“ও পোস্ট করল কেন?” থ্রেড'),tag:b('Victim-blaming · Support','ভুক্তভোগীকে দোষ · সহায়তা'),post:b('After a fictional person is harassed, comments focus on what they wore, posted or said instead of the abusive behavior.','একজন কাল্পনিক ব্যক্তি হয়রানির শিকার হওয়ার পর মন্তব্যগুলো অপমানকারীর আচরণের বদলে সে কী পরেছিল, পোস্ট করেছিল বা বলেছিল—সেদিকে যায়।'),human:b('The targeted person stops asking for help because every disclosure brings another round of blame.','প্রতিবার বললে নতুন করে দোষারোপ আসে বলে আক্রান্ত ব্যক্তি সাহায্য চাওয়া বন্ধ করে।'),safe:b('Keep responsibility on the harmful behavior and ask the target what support they want.','ক্ষতিকর আচরণের দায় সেখানেই রাখুন এবং আক্রান্ত ব্যক্তি কী সহায়তা চান জিজ্ঞেস করুন।'),signal:b('Victim-blaming can silence reporting and isolate the person targeted.','ভুক্তভোগীকে দোষারোপ অভিযোগ করা কমায় এবং আক্রান্ত ব্যক্তিকে একা করে।'),skills:['bystander','support']},
 {key:'report-dogpile',mode:'bystander',title:b('The Report Dogpile','দলবদ্ধ রিপোর্ট'),tag:b('Platform abuse · Silencing','প্ল্যাটফর্ম অপব্যবহার · কণ্ঠরোধ'),post:b('A group coordinates mass reports against a fictional student’s harmless post simply because they dislike the student.','একটি দল শুধু শিক্ষার্থীটিকে অপছন্দ করার কারণে তার নিরীহ পোস্টে সমন্বিত mass report করছে।'),human:b('The student temporarily loses access to an account used for class and club communication.','শিক্ষার্থীটি ক্লাস ও ক্লাব যোগাযোগে ব্যবহৃত অ্যাকাউন্টে সাময়িক প্রবেশাধিকার হারায়।'),safe:b('Do not misuse reporting tools; document coordinated harassment and support legitimate appeal/report paths.','রিপোর্টিং টুল অপব্যবহার করবেন না; সমন্বিত হয়রানির প্রমাণ রাখুন এবং বৈধ আপিল/রিপোর্ট পথ ব্যবহার করুন।'),signal:b('Safety tools can become harassment tools when a crowd weaponizes them.','ভিড় অপব্যবহার করলে নিরাপত্তা টুলও হয়রানির অস্ত্র হতে পারে।'),skills:['bystander','support']},
];

function modeChoices(mode:Mode,l:Locale,spec:Spec):Choice[]{
 const L=(en:string,bn:string)=>l==='en'?en:bn;
 const risky:Choice[]=[
  {id:'amplify',label:L('Share / react immediately','সাথে সাথে শেয়ার / রিঅ্যাক্ট'),helper:L('Act before checking','যাচাইয়ের আগে কাজ করি'),kind:'risk',delta:{reach:28,hostility:21,safety:-18,trust:-20},score:8,title:L('The ripple accelerates','প্রভাব দ্রুত ছড়ায়'),body:pick(spec.human,l)},
  {id:'attack',label:L('Add a harsh public comment','কঠোর পাবলিক মন্তব্য করি'),helper:L('Push back with anger','রাগ দিয়ে জবাব দিই'),kind:'risk',delta:{reach:16,hostility:29,safety:-19,trust:-22},score:12,title:L('The crowd gets hotter','ভিড় আরও উত্তপ্ত হয়'),body:pick(spec.human,l)},
  {id:'pause',label:L('Pause without amplifying','শেয়ার না করে থামি'),helper:L('Do not add another copy','আরেকটি কপি ছড়াই না'),kind:'neutral',delta:{reach:-3,hostility:-2,safety:4,trust:5},score:58,title:L('You remove one acceleration point','আপনি একটি ছড়ানোর পথ বন্ধ করেন'),body:L('You do not add reach, but the harmful or misleading content may continue without correction.','আপনি আর ছড়ান না, তবে ক্ষতিকর বা বিভ্রান্তিকর কনটেন্ট সংশোধন ছাড়া চলতে পারে।')},
  {id:'responsible',label:pick(spec.safe,l),helper:L('Slow down and protect people','থামুন, মানুষ ও তথ্যকে সুরক্ষিত রাখুন'),kind:mode==='bystander'||mode==='privacy'?'support':'safe',delta:{reach:-8,hostility:-11,safety:13,trust:17},score:88,title:L('The chain is interrupted','শেয়ার-চেইন থামে'),body:L('You reduce amplification and create space for verification, support or de-escalation.','আপনি ছড়িয়ে পড়া কমান এবং যাচাই, সহায়তা বা উত্তেজনা কমানোর সুযোগ তৈরি করেন।')}
 ];
 return risky;
}

function peaceChoices(mode:Mode,l:Locale,spec:Spec):Choice[]{
 const L=(en:string,bn:string)=>l==='en'?en:bn;
 return [
  {id:'best',label:pick(spec.safe,l),helper:L('Protect context, safety and agency','প্রেক্ষাপট, নিরাপত্তা ও নিয়ন্ত্রণ রক্ষা'),kind:mode==='bystander'||mode==='privacy'?'support':'safe',delta:{reach:-14,hostility:-16,safety:20,trust:22},score:97,title:L('A safer path becomes visible','আরও নিরাপদ পথ দেখা যায়'),body:L('The harmful chain loses momentum and the people affected keep more control over what happens next.','ক্ষতিকর চেইনের গতি কমে এবং আক্রান্ত মানুষ পরের পদক্ষেপে বেশি নিয়ন্ত্রণ রাখে।')},
  {id:'context',label:L('Add calm, limited context','শান্ত ও সীমিত প্রেক্ষাপট যোগ করি'),helper:L('Say only what can be supported','যতটুকু সমর্থিত ততটুকুই বলি'),kind:'safe',delta:{reach:-7,hostility:-17,safety:13,trust:18},score:91,title:L('Certainty becomes accountable','নিশ্চয়তা দায়বদ্ধ হয়'),body:L('People see uncertainty and boundaries instead of another confident accusation.','মানুষ আরেকটি নিশ্চিত অভিযোগের বদলে অনিশ্চয়তা ও সীমা দেখতে পায়।')},
  {id:'support',label:L('Support the person affected','আক্রান্ত ব্যক্তিকে সহায়তা করি'),helper:L('Ask what help they want','কী সহায়তা চান জিজ্ঞেস করি'),kind:'support',delta:{reach:-5,hostility:-9,safety:18,trust:16},score:92,title:L('Agency returns to the person','নিয়ন্ত্রণ আবার ব্যক্তির হাতে যায়'),body:L('Support follows the needs of the person affected instead of turning their experience into more content.','অভিজ্ঞতাকে আরও কনটেন্ট না বানিয়ে সহায়তা আক্রান্ত ব্যক্তির প্রয়োজন অনুযায়ী হয়।')}
 ];
}

function xray(mode:Mode,l:Locale,spec:Spec){
 const L=(en:string,bn:string)=>l==='en'?en:bn;
 const common=[
  {t:L('Slow-down signal','থামার সংকেত'),s:pick(spec.signal,l),b:L('A cue that should reduce confidence and increase verification or care.','এমন সংকেত যা আত্মবিশ্বাস কমিয়ে যাচাই বা যত্ন বাড়ানো উচিত।')},
  {t:L('Social proof','সামাজিক প্রমাণ'),s:L('Likes / forwards / comments','লাইক / ফরোয়ার্ড / কমেন্ট'),b:L('Popularity measures attention, not truth or safety.','জনপ্রিয়তা মনোযোগ দেখায়, সত্য বা নিরাপত্তা নয়।')},
  {t:L('Missing context','অনুপস্থিত প্রেক্ষাপট'),s:L('What is not shown?','কী দেখানো হয়নি?'),b:L('Ask what happened before, after, outside the crop, or outside the post.','পোস্টের আগে, পরে, কাটা অংশের বাইরে কী আছে জিজ্ঞেস করুন।')},
  {t:L('Human cost','মানুষের ক্ষতি'),s:L('Who carries the consequence?','পরিণতি কে বহন করে?'),b:L('A small digital action can shift risk, humiliation or fear onto another person.','ছোট ডিজিটাল কাজ অন্যের ওপর ঝুঁকি, অপমান বা ভয় চাপিয়ে দিতে পারে।')},
  {t:L('Better next move','ভালো পরের পদক্ষেপ'),s:pick(spec.safe,l),b:L('Responsible action protects evidence, context and the agency of people affected.','দায়িত্বশীল কাজ প্রমাণ, প্রেক্ষাপট ও আক্রান্ত মানুষের নিয়ন্ত্রণ রক্ষা করে।')}
 ];
 return common;
}

const shieldEn=['Recognize — name the harmful behavior without blaming the target.','Support — check in privately and ask what the person wants.','Preserve — keep only necessary evidence without recirculating harm.','Report — use an appropriate platform, institution or community pathway.','Escalate — credible threats may require trusted or official support.'];
const shieldBn=['Recognize — ক্ষতিকর আচরণটি চিহ্নিত করুন, আক্রান্ত ব্যক্তিকে দোষ দেবেন না।','Support — ব্যক্তিগতভাবে খোঁজ নিন এবং তিনি কী চান জিজ্ঞেস করুন।','Preserve — ক্ষতি না ছড়িয়ে শুধু প্রয়োজনীয় প্রমাণ রাখুন।','Report — উপযুক্ত প্ল্যাটফর্ম, প্রতিষ্ঠান বা কমিউনিটি পথে রিপোর্ট করুন।','Escalate — বিশ্বাসযোগ্য হুমকিতে বিশ্বস্ত বা অফিসিয়াল সহায়তা লাগতে পারে।'];

export function buildGeneratedScenarios(locale:Locale):Scenario[]{
 const L=(en:string,bn:string)=>locale==='en'?en:bn;
 return specs.slice(0,28).flatMap((spec,idx)=>contexts[locale].map((context,v)=>{
  const n=v+1;
  return {
   id:`lib-${spec.key}-${n}`,
   family:spec.mode,
   skills:spec.skills,
   title:pick(spec.title,locale),
   tag:`${pick(spec.tag,locale)} · ${context}`,
   intro:L('This is a fictional composite inspired by common documented patterns of online harm.','এটি অনলাইন ক্ষতির নথিভুক্ত সাধারণ ধরণ থেকে অনুপ্রাণিত একটি কাল্পনিক সমন্বিত দৃশ্য।'),
   post:`${context}: ${pick(spec.post,locale)}`,
   prompt:L('This reaches your screen. What do you do first?','এটি আপনার স্ক্রিনে এলো। আপনি প্রথমে কী করবেন?'),
   choices:modeChoices(spec.mode,locale,spec),
   peace:peaceChoices(spec.mode,locale,spec),
   xray:xray(spec.mode,locale,spec),
   human:pick(spec.human,locale),
   shield:(spec.mode==='bystander'||spec.mode==='privacy')?(locale==='en'?shieldEn:shieldBn):undefined
  } as Scenario;
 }));
}

const SESSION_KEY='ripple-session-scenarios-v2';
const HISTORY_KEY='ripple-scenario-history-v2';
const CURATED=['clip','meme','voice'];

function shuffle<T>(items:T[]):T[]{
 const a=[...items];
 if(typeof crypto!=='undefined'&&'getRandomValues' in crypto){
  const r=new Uint32Array(a.length);crypto.getRandomValues(r);
  for(let i=a.length-1;i>0;i--){const j=(r[i]??0)%(i+1);[a[i],a[j]]=[a[j]!,a[i]!]}
 } else {
  for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j]!,a[i]!]}
 }
 return a;
}

export function currentSessionIds(allIds:string[]):string[]{
 try{
  const saved=JSON.parse(localStorage.getItem(SESSION_KEY)||'[]') as string[];
  if(saved.length===3&&saved.every(id=>allIds.includes(id))) return saved;
  const history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]') as string[];
  if(history.length===0){
   localStorage.setItem(SESSION_KEY,JSON.stringify(CURATED));
   return CURATED;
  }
 }catch{}
 return rotateSessionIds(allIds);
}

export function rotateSessionIds(allIds:string[]):string[]{
 let history:string[]=[];
 try{history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]') as string[]}catch{}
 const current=(()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'[]') as string[]}catch{return []}})();
 const used=new Set([...history,...current]);
 let pool=allIds.filter(id=>!used.has(id));
 if(pool.length<3){history=[];pool=allIds.filter(id=>!current.includes(id))}
 const chosen=shuffle(pool).slice(0,3);
 const nextHistory=[...history,...current].filter((x,i,a)=>a.indexOf(x)===i).slice(-45);
 localStorage.setItem(HISTORY_KEY,JSON.stringify(nextHistory));
 localStorage.setItem(SESSION_KEY,JSON.stringify(chosen));
 return chosen;
}

export function clearSessionSelection(){
 localStorage.removeItem(SESSION_KEY);
}
